apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
data:
  django.yaml: |
    apiVersion: 1
    providers:
      - name: 'django'
        folder: 'Django'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /etc/grafana/provisioning/dashboards/django
